name: payment
description: A new Flutter project.
publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  webview_flutter: ^3.0.4








  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1


flutter_icons:
  android: "icon_app"
  ios: true
  image_path: "assets/images/icon_app.png"
  adaptive_icon_foreground: "assets/images/icon_app.png"
  adaptive_icon_background: "assets/images/icon_app.png"


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/


